### ISSUE TITLE
Error encountered: 404

### ISSUE THREAD

**Issue by Noor-Alsayed** [nestjs/azure-storage#149]
I did the exact code but I received this message? any idea?
{
  "messages": "Error encountered: 404",
  "statusCode": 500,
  "path": "/entities/company/cg",
  "timestamp": "2021-01-10T18:26:22.040Z"
}

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
