### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by kauandotnet** [nestjs/azure-storage#196]
❯ npm i @nestjs/azure-storage
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.0.1
npm ERR! Found: @nestjs/common@8.0.5
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.0.0" from @nestjs/azure-storage@2.1.1
npm ERR! node_modules/@nestjs/azure-storage
npm ERR!   @nestjs/azure-storage@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/azure-storage@3.0.0`
